export default [{ name: "Jumping Jacks", timing: "seconds", range: "high" },
{ name: "Punches", timing: "seconds", range: "mid" },
{ name: "Burpees", timing: "seconds", range: "mid" },
{ name: "Plank", timing: "seconds", range: "mid" },
{ name: "High Knees", timing: "reps", range: "mid" },
{ name: "Push-ups", timing: "reps", range: "mid" },
{ name: "Squats", timing: "reps", range: "high" },
{ name: "Pull-ups (or renegade rows)", timing: "reps", range: "low" },
{ name: "Mountain Climbers", timing: "seconds", range: "high" },
{ name: "Sit-ups", timing: "reps", range: "mid" },
{ name: "Squat Jumps", timing: "reps", range: "mid" },
{ name: "Lunges", timing: "reps", range: "mid" },
{ name: "Calf Raises", timing: "reps", range: "mid" },
{ name: "Russian Twists", timing: "reps", range: "mid" },
{ name: "Plank Jacks", timing: "seconds", range: "high" },
{ name: "Leg Raises", timing: "reps", range: "mid" },
{ name: "Tricep Dips", timing: "reps", range: "mid" },
{ name: "Side Lunges", timing: "reps", range: "mid" },
{ name: "Supermans", timing: "reps", range: "mid" },
{ name: "Box Jumps", timing: "reps", range: "high" },
{ name: "Bicycle Crunches", timing: "reps", range: "mid" },
{ name: "Inchworms", timing: "reps", range: "mid" },
{ name: "Plank to Push-up", timing: "reps", range: "mid" },
{ name: "Diamond Push-ups", timing: "reps", range: "mid" },
{ name: "Step-ups", timing: "reps", range: "mid" },
{ name: "Jump Rope", timing: "seconds", range: "mid" },
{ name: "Wall Sits", timing: "seconds", range: "high" },
{ name: "Tricep Push-ups", timing: "reps", range: "mid" },
{ name: "Wide Squats", timing: "reps", range: "mid" },
{ name: "Bear Crawls", timing: "reps", range: "mid" },
{ name: "Plank Variations", timing: "seconds", range: "mid" },
{ name: "Jump Lunges", timing: "reps", range: "mid" },
{ name: "Lateral Raises", timing: "reps", range: "mid" },
{ name: "V-Ups", timing: "reps", range: "mid" },
{ name: "Dips", timing: "reps", range: "mid" },
{ name: "Flutter Kicks", timing: "reps", range: "mid" },
{ name: "Plank Shoulder Taps", timing: "reps", range: "mid" },
{ name: "Climber Taps", timing: "reps", range: "mid" },
{ name: "Reverse Lunges", timing: "reps", range: "mid" },
{ name: "Boxer Shuffle", timing: "seconds", range: "mid" },
{ name: "Chair Pose", timing: "seconds", range: "mid" },
{ name: "Leg Curls", timing: "reps", range: "mid" },
{ name: "Cross Jacks", timing: "reps", range: "mid" },
{ name: "Push-up to Side Plank", timing: "reps", range: "mid" },
{ name: "Side Leg Lifts", timing: "reps", range: "mid" },
{ name: "Arm Circles", timing: "reps", range: "mid" },
{ name: "Seated Russian Twists", timing: "reps", range: "mid" },
{ name: "Wall Push-ups", timing: "reps", range: "low" },]